workflows:
  android-debug:
    name: Android Debug Build & Test
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.emfad.app"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
        - pattern: feature/*
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Make gradlew executable
        script: |
          chmod +x gradlew
      
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug --stacktrace --info --no-daemon
      
      - name: Run unit tests
        script: |
          ./gradlew testDebugUnitTest --continue --stacktrace
        test_report: app/build/test-results/testDebugUnitTest/TEST-*.xml
      
      - name: Run Android lint
        script: |
          ./gradlew lintDebug --stacktrace
        test_report: app/build/reports/lint-results-debug.xml
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/lint-results-debug.html
      - app/build/test-results/**/*.xml
    
    publishing:
      email:
        recipients:
          - info@emfad.de
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.emfad.app"
        GOOGLE_PLAY_TRACK: internal
        # Auto-generate keystore environment variables
        CM_KEYSTORE_PATH: "$CM_BUILD_DIR/release.keystore"
        CM_KEYSTORE_PASSWORD: "emfad123"
        CM_KEY_ALIAS: "emfad_key"
        CM_KEY_PASSWORD: "emfad123"
      java: 17
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: v*.*.*
          include: true
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Make gradlew executable
        script: |
          chmod +x gradlew
      
      - name: Generate release keystore
        script: |
          keytool -genkey -v \
            -keystore $CM_KEYSTORE_PATH \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias $CM_KEY_ALIAS \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            -dname "CN=EMFAD, OU=Development, O=EMFAD GmbH, L=Bexley, ST=England, C=GB"
      
      - name: Build release APK
        script: |
          ./gradlew assembleRelease --stacktrace --info --no-daemon
      
      - name: Build Android App Bundle
        script: |
          ./gradlew bundleRelease --stacktrace --info --no-daemon
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - info@emfad.de
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
